spring:
  application:
    name: challenge-softteck

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      resourceserver:
        jwt:
          public-key-location: classpath:keys/jwt.pub

# Firebase Configuration
firebase:
  project-id: ${FIREBASE_PROJECT_ID:challenge-softteck}
  service-account-key: ${FIREBASE_SERVICE_ACCOUNT_KEY:firebase-service-account.json}

# Google OAuth Configuration
google:
  accepted-client-ids:
    - 326016549814-0ra7e82555s4fis8l3u16u1h0u9vsp89.apps.googleusercontent.com
    - 326016549814-ge7kifevf5504d0pgpvpvq6o5pisnnlf.apps.googleusercontent.com
    - 326016549814-nr0ltdvl8q9sjkv9bgbjkil5s6ad8hg5.apps.googleusercontent.com
    - 326016549814-0pgodn7bp2qcun8ve0puapufcnv8na34.apps.googleusercontent.com

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    br.com.fiap.challenge_softteck: DEBUG
    com.google.firebase: INFO
    com.google.cloud.firestore: INFO