CREATE TABLE TB_USER_MAP (
    SUB                     VARCHAR2(255)   PRIMARY KEY,
    USER_UUID               RAW(16)         NOT NULL,
    CREATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP,
    IS_ACTIVE               CHAR(1)         DEFAULT 'Y' NOT NULL
);

CREATE TABLE TB_FORM (
    ID                      NUMBER(19)      PRIMARY KEY,
    CODE                    VARCHAR2(40)    UNIQUE NOT NULL,
    NAME                    VARCHAR2(255)   NOT NULL,
    FORM_TYPE               VARCHAR2(32)    NOT NULL, -- CHECKIN | SELF_ASSESSMENT | CLIMATE | REPORT
    DESCRIPTION             VARCHAR2(255)   NULL,
    IS_ACTIVE               CHAR(1)         DEFAULT 'Y' NOT NULL, -- Y/N
    PERIODICITY_DAYS        NUMBER(4)       NOT NULL, -- ex.: 1 = diário, 7 = semanal, 90 = 3 meses…
    CREATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP
);

CREATE TABLE TB_QUESTION (
    ID                      NUMBER(19)      PRIMARY KEY,
    FORM_ID                 NUMBER(19)      NOT NULL REFERENCES TB_FORM(ID) ON DELETE CASCADE,
    ORDINAL                 NUMBER(4)       NOT NULL,
    TEXT                    VARCHAR2(1000)  NOT NULL,
    QTYPE                   VARCHAR2(20)    NOT NULL,  -- CHOICE | SCALE | TEXT
    SCALE_MIN               NUMBER(3),      -- se QTYPE = SCALE
    SCALE_MAX               NUMBER(3)       -- idem
);

CREATE TABLE TB_OPTION (
    ID                      NUMBER(19)      PRIMARY KEY,
    QUESTION_ID             NUMBER(19)      NOT NULL REFERENCES TB_QUESTION(ID) ON DELETE CASCADE,
    ORDINAL                 NUMBER(4)       NOT NULL,
    VALUE                   VARCHAR2(100)   NOT NULL,
    LABEL                   VARCHAR2(255)   NOT NULL
);

CREATE TABLE TB_FORM_RESPONSE (
    ID                      NUMBER(19)      PRIMARY KEY,
    FORM_ID                 NUMBER(19)      NOT NULL REFERENCES TB_FORM(ID),
    USER_UUID               RAW(16)         NOT NULL,
    ANSWERED_AT             TIMESTAMP       DEFAULT SYSTIMESTAMP
);

CREATE TABLE TB_ANSWER (
    ID                      NUMBER(19)      PRIMARY KEY,
    RESPONSE_ID             NUMBER(19)      NOT NULL REFERENCES TB_FORM_RESPONSE(ID) ON DELETE CASCADE,
    QUESTION_ID             NUMBER(19)      NOT NULL REFERENCES TB_QUESTION(ID),
    OPTION_ID               NUMBER(19),     -- se CHOICE
    VALUE_NUMERIC           NUMBER(10,2),   -- se SCALE
    VALUE_TEXT              VARCHAR2(4000)  -- se TEXT
);

CREATE TABLE TB_USER_PREF (
    USER_UUID               RAW(16)         PRIMARY KEY,
    NOTIF_ENABLED           CHAR(1)         DEFAULT 'Y',
    LAST_CHECKIN_REMINDER   TIMESTAMP,
    LAST_SELF_REMINDER      TIMESTAMP,
    LAST_CLIMATE_REMINDER   TIMESTAMP
);

CREATE TABLE TB_REMINDER (
    ID                      NUMBER(19)      PRIMARY KEY,
    USER_UUID               RAW(16)         NOT NULL,
    FORM_ID                 NUMBER(19)      NOT NULL,
    SCHEDULED_AT            TIMESTAMP       NOT NULL,
    SENT_AT                 TIMESTAMP,
    TYPE                    VARCHAR2(32)    NOT NULL    -- DAILY | 3M | 6M | CUSTOM
);

CREATE INDEX IX_ANSWER_Q ON TB_ANSWER (QUESTION_ID);
CREATE INDEX IX_RESPONSE_USER ON TB_FORM_RESPONSE (USER_UUID);
CREATE INDEX IX_REMINDER_USER_FORM ON TB_REMINDER (USER_UUID, FORM_ID);

CREATE SEQUENCE SQ_FORM             START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_QUESTION         START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_OPTION           START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_FORM_RESPONSE    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_ANSWER           START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_REMINDER         START WITH 1 INCREMENT BY 1;